CREATE TABLE `customer_dtl` (
   `CUSTOMER_ID` int NOT NULL AUTO_INCREMENT,
   `CUSTOMER_NAME` varchar(30) DEFAULT NULL,
   `FATHER_NAME` varchar(30) DEFAULT NULL,
   `GENDER` varchar(1) DEFAULT NULL,
   `CUSTOMER_DOB` date DEFAULT NULL,
   `CONTACT_NO` varchar(15) DEFAULT NULL,
   `UID_NO` varchar(12) DEFAULT NULL,
   `VOTER_ID` varchar(30) DEFAULT NULL,
   `CUSTOMER_EMAIL` varchar(45) DEFAULT NULL,
   `ADDRESS` varchar(30) DEFAULT NULL,
   `DISTRICT` varchar(30) DEFAULT NULL,
   `STATE` varchar(30) DEFAULT NULL,
   `PINCODE` varchar(6) DEFAULT NULL,
   PRIMARY KEY (`CUSTOMER_ID`)
 ) 